STRINGS.NAMES.ACHIVBOOK_BIRDS = STRINGS.NAMES.BOOK_BIRDS
STRINGS.RECIPE_DESC.ACHIVBOOK_BIRDS = STRINGS.RECIPE_DESC.BOOK_BIRDS

STRINGS.NAMES.ACHIVBOOK_GARDENING = STRINGS.NAMES.BOOK_GARDENING
STRINGS.RECIPE_DESC.ACHIVBOOK_GARDENING = STRINGS.RECIPE_DESC.BOOK_GARDENING

STRINGS.NAMES.ACHIVBOOK_SLEEP = STRINGS.NAMES.BOOK_SLEEP
STRINGS.RECIPE_DESC.ACHIVBOOK_SLEEP = STRINGS.RECIPE_DESC.BOOK_SLEEP

STRINGS.NAMES.ACHIVBOOK_BRIMSTONE = STRINGS.NAMES.BOOK_BRIMSTONE
STRINGS.RECIPE_DESC.ACHIVBOOK_BRIMSTONE = STRINGS.RECIPE_DESC.BOOK_BRIMSTONE

STRINGS.NAMES.ACHIVBOOK_TENTACLES = STRINGS.NAMES.BOOK_TENTACLES
STRINGS.RECIPE_DESC.ACHIVBOOK_TENTACLES = STRINGS.RECIPE_DESC.BOOK_TENTACLES

STRINGS.ALLACHIVCURRENCY={
[1] = "Logro completado [",
[2] = "]",
[3] = "   ",
[4] = "Conseguido ",
[5] = " Puntos",
[6] = "[",
[7] = "Ver logros",
[8] = "Ver recompensas",
[9] = "Has completado: ",
[10] = "Obtuviste：x",
[11] = "Moose/Goose:",
[12] = "Antlion:",
[13] = "Bearger:",
[14] = "Deerclops:",
[15] = "Configuraciones",
[16] = "Acercar",
[17] = "Alejar",
[18] = "Reiniciar recompensas",
[19] = "Cambiar idioma",
}

STRINGS.GUI={
["achievementTitle"] = "Puntos de logros",
["levelTitle"] = "Nivel de experiencia",
["close"] = "Cerrar",
["reset"] = "Reiniciar",
["resetAchievments"] = "Reiniciar removerá todas las recompensas y reembolsará el 85% de puntos de logros",
["food"] = "Comida",
["life"] = "Vida",
["work"] = "Tareas",
["like"] = "Fama",
["pain"] = "Dolor",
["fight"] = "Lucha",
["hunt"] = "Cacería",
["boss"] = "Jefes",
["misc"] = "Extra",
["emer"] = "Emer",
["mile"] = "Tiempo",
["attributes"] = "Atributos",
["abilities"] = "Habilidades",
["crafting"] = "Creación",
["attributelabels"] = "Hambre:\nSanidad:\nSalud:\nDaño:\nResistencia:\nVelocidad:\nResistencia al calor:\nResistencia al frío:\n",
["attributeunits"] = "\n\n%\n%\n%\n\n\n",
["resetlevel"] = "Reiniciar removerá todas las mejoras y reembolsará el 85% de puntos de logros",
["iteminfo"] = "Las mejoras se aplican solo a los valores base.\n Estos valores son los valores definitivos.",
["availablePoints"] = "Puntos \n disponibles: \n ",
["overallxp"] = "Experiencia total: ",
["foodlist"] = "Lista de comidas",
["attributecost"] = "Coste",
}

STRINGS.ALLACHIVNAME={
--ACHIEVEMENTS
--Food
["firsteat"] = "Primer bocado",
["eatrata"] = "Mario is a rat", --Rata Cusca
["eatfish"] = "Prefiero el pescado",
["eatturkey"] = "Acción de gracias",
["eathot"] = "Para una noche helada",
["eatcold"] = "Para un día caluroso",
["danding"] = "Estómago de hierro",
["eatmole"] = "Fiesta",
["eatwaffle"] = "A Desayunar",
["supereat"] = "Degustador",
["alldiet"] = "Comelón",
--Life
["noob"] = "Peor que Novato",
["tooyoung"] = "¡El cielo se cae!",
["rose"] = "Muerte rosada",
["shroom"] = "Venenoso",
["rot"] = "Tóxico", --Envenenado
["deathalot"] = "Acostumbrándome",
["secondchance"] = "Segunda oportunidad",
["messiah"] = "Héroe", --Mesías
["sleeptent"] = "Dulce Hogar",
["sleepsiesta"] = "Refrescante", --Siestas reparadoras
["reviveamulet"] = "Inmatable", 
["feedplayer"] = "Cocinero comunitario",
--Work
["nature"] = "Ecologista",
["fishmaster"] = "Pescador",
["pickappren"] = "Recolector",
["pickmaster"] = "Recolector compulsivo",
["chopappren"] = "Señor Castor",
["chopmaster"] = "Señor Bearger ",
["mineappren"] = "Minero",
["minemaster"] = "Geólogo",
["cookappren"] = "Chef 3 estrellas", --Chef 4 estrellas
["cookmaster"] = "Chef 5 estrellas", --Gordon Ramsay
["buildappren"] = "Artesano",
["buildmaster"] = "Inventor",
--Like
["goodman"] = "Aliado porcino",
["brother"] = "Aliado peludo",
["catperson"] = "Amante de los gatos",
["spooder"] = "Mamá Araña",
["evil"] = "¡Pequeñas molestias!",
["birdclop"] = "Paternidad", --Típico adolescente
["pet"] = "Seguidor leal",
["lavae"] = "Un cálido amigo",
["fuzzy"] = "Un amigo inesperado",
--Pain
["burn"] = "Ave Fénix",
["freeze"] = "Cubo de hielo",
["sleep"] = "Una siesta rápida", 
["starve"] = "Inanición",
["nosanity"] = "Esquizofrenia",
["icebody"] = "Hipotermia",
["firebody"] = "Hipertermia",
["moistbody"] = "Llueve sobre mi", --Amante del agua
["evilflower"] = "Flores malévolas",
["roses"] = "Reina de rosas",
["drown"] = "Mejor usa un bote",
["lightning"] = "Sobrecargado", 
--Fight
["angry"] = "Sádico",
["tank"] = "Escudo de carne",
["fortress"] = "Fortaleza",
["dmgnodmg"] = "Muy lento!",
["whipit"] = "Azótalos!",
["whack"] = "Es más de 9000!",
["bullseye"] = "Tiro Al Blanco",
["sheep"] = "Imparable",
["tentacruel"] = "Tenta Cruel",
--Hunt
["goatperd"] = "Corto circuito",
["mossling"] = "A dormir, pequeños",
["weetusk"] = "Cazador cazado",
["tentacool"] = "Tentacool", --Medusa
["treeguard"] = "Guardianes del bosque",
["varg"] = "Suelte a los sabuesos",
["koalefant"] = "Cazador de  marfil",
["monkey"] = "Nada de monadas",
["horrorhound"] = "T-Virus", --Zombies
["slurtle"] = "Pegajoso",
["werepig"] = "Licantropía",
--Boss
["santa"] = "Niño malo",
["dragonfly"] = "Dragón sin princesa",
["malbatross"] = "Monstruo marino",
["knight"] = "Caballero blanco",
["bishop"] = "Alfil fuera de juego",
["rook"] = "Torre derrocada",
["minotaur"] = "Minotauro caído",
["ancient"] = "La raiz de todo...",
["rigid"] = "Nada es imposible",
["queen"] = "Reina destronada",
["crabking"] = "Sr. Cangrejo",
["king"] = "Un nuevo rey/reina",
--Misc
["intogame"] = "Un nuevo comienzo",
["superstar"] = "Cazador de logros",
["trader"] = "Comerciante",
["knowledge"] = "Conocimiento antigüo",
["dance"] = "Alma de la fiesta",
["teleport"] = "Viaje rápido",
["birchnut"] = "Limpieza",
--Emer
["eatgold"] = "Gusto costoso",
["eatefc"] = "Para chuparse los dedos",
["eathorn"] = "Uy...",
["eateye"] = "Eye me equivoque",
["emerald"] = "Emerville",
["goldcoin"] = "Fincas millonarias",
["baronsuit"] = "Nobleza",
--["luck"] = "La suerte me sonríe",
--["citrin"] = "Amarillo citrino",
--["amber"] = "Naranja ámbar",
--["saddle"] = "Hora de montar",
--["banana"] = "Involución",
--["moonrock"] = "Selenólogo",
--["gnome"] = "Los Siete Enanitos",
--Mile
["all"] = "Completista",
["longage"] = "El pasar del tiempo",
["oldage"] = "Gran dedicación",
["walkalot"] = "Maratonista",
["stopalot"] = "Petrificado",
["caveage"] = "Cavernícola",
["rider"] = "Vaquero",
["fullsanity"] = "Estable de mente",
["fullhunger"] = "Bien alimentado",
["pacifist"] = "Pacifista",
}

STRINGS.PERKNAME={
--PERKS
["hungerup"] = "Hambre +",
["sanityup"] = "Sanidad +",
["healthup"] = "Salud +",
["crit"] = "Golpes críticos",
["scale"] = "Tamaño +",
["krampusxmas"] = "Suertudo",
["cookmaster"] = "Chef 5 estrellas",
["pickmaster"] = "Gran recolector",
["artsdegree"] = "Licenciatura en artes",
["minemaster"] = "Experto minero",
["ancientstation"] = "Sabiduría antigüa",
["lunarcraft"] = "Selenólogo experto",
["businessowner"] = "Dueño de negocio",
["animallover"] = "Amigo del bosque",
}

STRINGS.ALLACHIVDESC={
--ACHIEVEMENTS
--Food
["firsteat"] = "Come por primera vez",
["eatrata"] = "Come ratatouille "..allachiv_eventdata["eatrata"].." veces",
["eatfish"] = "Come palitos de pescado "..allachiv_eventdata["eatfish"].." veces",
["eatturkey"] = "Come cenas de pavo "..allachiv_eventdata["eatturkey"].." veces",
["eathot"] = "Come "..allachiv_eventdata["eathot"].." platillos que te enfríen",
["eatcold"] = "Come "..allachiv_eventdata["eatcold"].." platillos que te calienten",
["danding"] = "Come "..allachiv_eventdata["danding"].." lasagnas monstruosas",
["eatmole"] = "Come guacamole "..allachiv_eventdata["eatmole"].." veces",
["eatwaffle"] = "Come waffles "..allachiv_eventdata["eatwaffle"].." veces",
["supereat"] = "Come "..allachiv_eventdata["supereat"].." platillos",
["alldiet"] = "Come todas las recetas de la cacerola",
--Life
["noob"] = "Muere a causa de Charlie",
["tooyoung"] = "Muere a causa de un meteorito",
["rose"] = "Muere por recoger una rosa",
["shroom"] = "Muere por comer un hongo rojo",
["rot"] = "Muere a causa de gas venenoso",
["deathalot"] = "Muere "..allachiv_eventdata["deathalot"].." veces",
["secondchance"] = "Revive gracias a una efigie de carne",
["messiah"] = "Revive a otros jugadores "..allachiv_eventdata["messiah"].." veces",
["sleeptent"] = "Duerme "..allachiv_eventdata["sleeptent"].." veces en una tienda",
["sleepsiesta"] = "Toma una siesta "..allachiv_eventdata["sleepsiesta"].." veces",
["reviveamulet"] = "Revive "..allachiv_eventdata["reviveamulet"].." veces con un amuleto",
["feedplayer"] = "Alimenta a otros "..allachiv_eventdata["feedplayer"].." veces con platillos",
--Work
["nature"] = "Planta "..allachiv_eventdata["nature"].." árboles o semillas",
["fishmaster"] = "Atrapa "..allachiv_eventdata["fishmaster"].." peces",
["pickappren"] = "Recoge "..allachiv_eventdata["pickappren"].." objetos",
["pickmaster"] = "Recoge "..allachiv_eventdata["pickmaster"].." objetos",
["chopappren"] = "Tala o cava "..allachiv_eventdata["chopappren"].." árboles",
["chopmaster"] = "Tala o cava "..allachiv_eventdata["chopmaster"].." árboles",
["mineappren"] = "Mina "..allachiv_eventdata["mineappren"].." rocas",
["minemaster"] = "Mina "..allachiv_eventdata["minemaster"].." rocas",
["cookappren"] = "Cocina "..allachiv_eventdata["cookappren"].." platillos de la cacerola",
["cookmaster"] = "Cocina "..allachiv_eventdata["cookmaster"].." platillos de la cacerola",
["buildappren"] = "Crea "..allachiv_eventdata["buildappren"].." objetos",
["buildmaster"] = "Crea "..allachiv_eventdata["buildmaster"].." objetos",
--Like
["goodman"] = "Hazte amigo de "..allachiv_eventdata["goodman"].." pigmen",
["brother"] = "Hazte amigo de "..allachiv_eventdata["brother"].." bunnymen",
["catperson"] = "Hazte amigo de "..allachiv_eventdata["catperson"].." catcoons",
["spooder"] = "Hazte amigo de "..allachiv_eventdata["spooder"].." arañas",
["evil"] = "Hazte amigo de "..allachiv_eventdata["evil"].." mandrágoras",
["birdclop"] = "Incuba un huevo de tallbird",
["pet"] = "Adopta a tu mascota favorita",
["lavae"] = "Hazte amigo de una larva de lava",
["fuzzy"] = "Alimenta a Antlion "..allachiv_eventdata["fuzzy"].." piedras térmicas",
--Pain
["burn"] = "Incéndiate",
["freeze"] = "Congélate",
["sleep"] = "Desmáyate por el cansancio",
["starve"] = "Ten inanición durante "..(allachiv_eventdata["starve"]/60).." minutos",
["nosanity"] = "Mantente insano durante "..(allachiv_eventdata["nosanity"]/60).." minutos",
["icebody"] = "Congélate durante "..(allachiv_eventdata["icebody"]/60).." minutos",
["firebody"] = "Sobrecaliéntate durante "..(allachiv_eventdata["firebody"]/60).." minutos",
["moistbody"] = "Permanece empapado durante "..(allachiv_eventdata["moistbody"]/60).." minutos",
["evilflower"] = "Recoge "..allachiv_eventdata["evilflower"].." flores malévolas",
["roses"] = "Recoge "..allachiv_eventdata["roses"].." rosas",
["drown"] = "Intenta nadar en el océano",
["lightning"] = "Deja que te caiga un rayo",
--Fight
["angry"] = "Inflinge "..allachiv_eventdata["angry"].." puntos de daño",
["tank"] = "Recibe "..allachiv_eventdata["tank"].." puntos de daño",
["fortress"] = "Recibe "..allachiv_eventdata["fortress"].." puntos de daño",
["dmgnodmg"] = "Inflinge "..(allachiv_eventdata["dmgnodmg"]/1000).."mil de daño sin recibir daño",
["whipit"] = "Inflinge "..allachiv_eventdata["whipit"].." de daño con cualquier látigo",
["whack"] = "Inflinge "..(allachiv_eventdata["whack"]/1000).."mil de daño con un bastón",
["bullseye"] = "Bulls-Eye"..(allachiv_eventdata["bullseye"]/1000).."mil de daño con blow darts",
["sheep"] = "Mata, por tu propia cuenta, a ewecus",
["tentacruel"] = "Mata, por tu propia cuenta, "..allachiv_eventdata["tentacruel"].." pilares de tentáculos",
--Hunt
["goatperd"] = "Mata "..allachiv_eventdata["goatperd"].." volt-goats sobrecargadas",
["mossling"] = "Mata "..allachiv_eventdata["mossling"].." moslings dormidos",
["weetusk"] = "Mata "..allachiv_eventdata["weetusk"].." Wee MacTusks",
["tentacool"] = "Mata "..allachiv_eventdata["tentacool"].." tentáculos",
["treeguard"] = "Mata "..allachiv_eventdata["treeguard"].." guardianes de los árboles",
["varg"] = "Mata "..allachiv_eventdata["varg"].." vargs",
["koalefant"] = "Mata "..allachiv_eventdata["koalefant"].." koalefantes",
["monkey"] = "Mata "..allachiv_eventdata["monkey"].." monos de las cuevas",
["horrorhound"] = "Mata "..allachiv_eventdata["horrorhound"].." sabuesos revividos",
["slurtle"] = "Mata "..allachiv_eventdata["slurtle"].." slurtles",
["werepig"] = "Mata "..allachiv_eventdata["werepig"].." were-pigs",
--Boss
["santa"] = "Derrota a Klaus",
["dragonfly"] = "Derrota a Dragonfly",
["malbatross"] = "Derrota a Malbatross",
["knight"] = "Derrota a Shadow Knight Level 3",
["bishop"] = "Derrota a Shadow Bishop Level 3",
["rook"] = "Derrota a Shadow Rook Level 3",
["minotaur"] = "Derrota a Ancient Guardian",
["ancient"] = "Derrota a Ancient Fuelreaver",
["rigid"] = "Derrota a Misery Toadstool",
["queen"] = "Derrota a Bee Queen",
["crabking"] = "Derrota a Rey Cangrejo",
["king"] = "Derrota a los jefes de las estaciones",
--Misc
["intogame"] = "Entra al juego",
["superstar"] = "Gasta "..allachiv_eventdata["superstar"].." estrellas",
["trader"] = "Vende "..allachiv_eventdata["trader"].." baratijas a cambio de oro",
["knowledge"] = "Aprende una receta antigüa",
["dance"] = "Diviértete con tus amigos",
["teleport"] = "Teletransportate "..allachiv_eventdata["teleport"].." veces",
["birchnut"] = "Tala "..allachiv_eventdata["birchnut"].." abedules mostruosos",
--Emer
["eatgold"] = "Come palillo de tambor/huevos dorado en oro "..allachiv_eventdata["eatgold"].." veces",
["eatefc"] = "Come Pollo Frito de Emerville "..allachiv_eventdata["eatefc"].." veces",
["eathorn"] = "Come cuerno de Guardián "..allachiv_eventdata["eathorn"].." vez",
["eateye"] = "Come ojo de Deerclops "..allachiv_eventdata["eateye"].." vez",
["emerald"] = "Posee "..allachiv_eventdata["emerald"].." gemas verdes",
["goldcoin"] = "Posee "..allachiv_eventdata["goldcoin"].." monedas de oro",
["baronsuit"] = "Posee "..allachiv_eventdata["baronsuit"].." Baron's suit",
--["luck"] = "Consigue el saco de Krampus",
--["citrin"] = "Posee "..allachiv_eventdata["citrin"].." gemas amarillas",
--["amber"] = "Posee "..allachiv_eventdata["amber"].." gemas naranjas",
--["saddle"] = "Crea una Montura Glossamer",
--["banana"] = "Ten "..allachiv_eventdata["banana"].." bananas de cueva cocinadas",
--["moonrock"] = "Consigue "..allachiv_eventdata["moonrock"].." rocas lunares",
--["gnome"] = "Consigue "..allachiv_eventdata["gnome"].." gnomos",
--Mile
["all"] = "Completa todos los logros",
["longage"] = "Sobrevive "..allachiv_eventdata["longage"].." días",
["oldage"] = "Sobrevive "..allachiv_eventdata["oldage"].." días",
["walkalot"] = "Camina "..(allachiv_eventdata["walkalot"]/60).." minutos",
["stopalot"] = "Permanece inmóbil "..(allachiv_eventdata["stopalot"]/60).." minutos",
["caveage"] = "Permanece "..(allachiv_eventdata["caveage"]/60).." minutos en las cuevas",
["rider"] = "Monta un Beefalo por "..(allachiv_eventdata["rider"]/60).." minutos",
["fullsanity"] = "Mantén tu sanidad sobre 95% por "..(allachiv_eventdata["fullsanity"]/60).." minutos",
["fullhunger"] = "Mantén tu hambre sobre 95% por "..(allachiv_eventdata["fullhunger"]/60).." minutos",
["pacifist"] = "No hagas daño por "..(allachiv_eventdata["pacifist"]/60).." minutos",
}

STRINGS.PERKDESC={
--PERKS
["hungerup"] = "Aumenta el hambre en "..allachiv_coindata["hungerup"],
["sanityup"] = "Aumenta la sanidad en "..allachiv_coindata["sanityup"],
["healthup"] = "Aumenta la salud en "..allachiv_coindata["healthup"],
["crit"] = "Aumenta la probabilidad de duplicar el daño en "..(allachiv_coindata["crit"]*100).."%",
["scale"] = "Aumenta el tamaño del personaje en "..(math.ceil(allachiv_coindata["scale"]*100)).."%",
["krampusxmas"] = "Aumenta la aparición del saco de Krampus en "..(math.ceil(allachiv_coindata["krampusxmas"]*100)).."%",
["cookmaster"] = "Cocina platillos en la cacerola  instantáneamente",
["pickmaster"] = "Duplica los objetos recolectados",
["artsdegree"] = "Gana la habilidad de crear flautas magicas.",
["minemaster"] = "Mina piedras instantaneamente",
["ancientstation"] = "Gana la habilidad de crear cosas avanzadas de la Estación de Pseudo-Ciencia Antigüa",
["lunarcraft"] = "Gana la habilidad de crear objetos lunares",
["businessowner"] = "Gana la habilidad de crear estructuras para comenzar un negocio",
["animallover"] = "Los animales no se asustarán de tí",
}

STRINGS.ALLACHIVINFO={
--Food
["firsteat"] = "ha comido por primera vez",
["eatrata"] = "ha comido "..allachiv_eventdata["eatrata"].." ratatouilles",
["eatfish"] = "ha comido "..allachiv_eventdata["eatfish"].." palitos de pescado",
["eatturkey"] = "ha comido "..allachiv_eventdata["eatturkey"].." cenas de pavo",
["eathot"] = "ha comido para prevenir el frío un total de "..allachiv_eventdata["eathot"].." veces",
["eatcold"] = "ha comido para prevenir el calor un total de "..allachiv_eventdata["eatcold"].." veces",
["danding"] = "ha comido "..allachiv_eventdata["danding"].." lasagnas monstruosas",
["eatmole"] = "ha comido "..allachiv_eventdata["eatmole"].." guacamoles",
["eatwaffle"] = "ha comido "..allachiv_eventdata["eatwaffle"].." waffles",
["supereat"] = "ha comido "..allachiv_eventdata["supereat"].." platillos",
["alldiet"] = "ha comido todos los platillos preparables en la cacerola",
--Life
["noob"] = "ha sido asesinado por Charlie",
["tooyoung"] = "ha muerto a causa de meteoritos",
["rose"] = "ha muerto por recoger una rosa",
["shroom"] = "he muerto por comer un hongo rojo",
["rot"] = "ha sucumbido en una nube de esporas",
["deathalot"] = "ha muerto "..allachiv_eventdata["deathalot"].." veces",
["secondchance"] = "ha revivido gracias a una efigie de carne",
["messiah"] = "ha revivido a otros "..allachiv_eventdata["messiah"].." veces",
["sleeptent"] = "ha dormido "..allachiv_eventdata["sleeptent"].." veces en una tienda",
["sleepsiesta"] = "ha tomado una siesta "..allachiv_eventdata["sleepsiesta"].." veces",
["reviveamulet"] = "ha revivido "..allachiv_eventdata["reviveamulet"].." veces con un amuleto",
["feedplayer"] = "ha alimentado a otros jugadores "..allachiv_eventdata["feedplayer"].." veces",
--Work
["nature"] = "ha plantado "..allachiv_eventdata["nature"].." árboles o semillas",
["fishmaster"] = "ha atrapado "..allachiv_eventdata["fishmaster"].." peces",
["pickappren"] = "ha recolectado "..allachiv_eventdata["pickappren"].." veces",
["pickmaster"] = "ha recogido objetos "..allachiv_eventdata["pickmaster"].." veces",
["chopappren"] = "ha talado o cavado "..allachiv_eventdata["chopappren"].." árboles",
["chopmaster"] = "ha talado o cavado "..allachiv_eventdata["chopmaster"].." árboles",
["mineappren"] = "ha minado "..allachiv_eventdata["mineappren"].." rocas",
["minemaster"] = "ha minado "..allachiv_eventdata["minemaster"].." rocas",
["cookappren"] = "ha cocinado "..allachiv_eventdata["cookappren"].." platillos de la cacerola",
["cookmaster"] = "ha cocinado "..allachiv_eventdata["cookmaster"].." recetas de la cacerola",
["buildappren"] = "ha creado "..allachiv_eventdata["buildappren"].." objetos",
["buildmaster"] = "ha creado objetos "..allachiv_eventdata["buildmaster"].." veces",
--Like
["goodman"] = "Se ha hecho amigo de Pigmen "..allachiv_eventdata["goodman"].." veces",
["brother"] = "se ha hecho amigo de Bunnymen "..allachiv_eventdata["brother"].." veces",
["catperson"] = "se ha hecho amigo de Catcoons "..allachiv_eventdata["catperson"].." veces",
["spooder"] = "se ha hecho amigo de "..allachiv_eventdata["spooder"].." arañas",
["evil"] = "se ha hecho amigo de "..allachiv_eventdata["evil"].." mandrágoras",
["birdclop"] = "ha incubado el huevo del pájaro con un solo ojo",
["pet"] = "ha conseguido un purrrfecto amigo para sus aventuras",
["lavae"] = "se amigó con una larva de lava",
["fuzzy"] = "ha alimentado al vigilante del desierto con piedras térmicas",
--Pain
["burn"] = "se ha envuelto en llamas",
["freeze"] = "se ha congelado",
["sleep"] = "se ha desmayado por el cansancio",
["starve"] = "ha permanecido con inanición durante "..(allachiv_eventdata["starve"]/60).." minutos",
["nosanity"] = "ha permanecido completamente insano por "..(allachiv_eventdata["nosanity"]/60).." minutos",
["icebody"] = "ha permanecido congelado por "..(allachiv_eventdata["icebody"]/60).." minutos",
["firebody"] = "ha permanecido sobrecalentado por "..(allachiv_eventdata["firebody"]/60).." minutos",
["moistbody"] = "ha permanecido húmedo por "..(allachiv_eventdata["moistbody"]/60).." minutos",
["evilflower"] = "ha recogido "..allachiv_eventdata["evilflower"].." flores malévolas",
["roses"] = "ha recogido "..allachiv_eventdata["roses"].." rosas",
["drown"] = "se ha ahogado intentando nadar",
["lightning"] = "fue golpeado por un rayo",
--Hunt
["goatperd"] = "ha matado "..allachiv_eventdata["goatperd"].." volt-goats sobrecargadas",
["mossling"] = "ha matado "..allachiv_eventdata["mossling"].." moslings dormidos",
["weetusk"] = "ha matado "..allachiv_eventdata["weetusk"].." Wee MacTusks",
["tentacool"] = "ha acabado con "..allachiv_eventdata["tentacool"].." tentáculos",
["treeguard"] = "ha matado "..allachiv_eventdata["treeguard"].." guardianes del bosque",
["varg"] = "ha matado "..allachiv_eventdata["varg"].." vargs",
["koalefant"] = "ha matado "..allachiv_eventdata["koalefant"].." koalefantes",
["monkey"] = "ha matado "..allachiv_eventdata["monkey"].." monos de las cuevas",
["horrorhound"] = "ha matado "..allachiv_eventdata["horrorhound"].." sabuesos revividos",
["slurtle"] = "ha matado "..allachiv_eventdata["slurtle"].." slurtles",
["werepig"] = "ha matado "..allachiv_eventdata["werepig"].." were-pigs",
--Fight
["angry"] = "ha inflingido "..allachiv_eventdata["angry"].." puntos de daño",
["tank"] = "ha recibido "..allachiv_eventdata["tank"].." puntos de daño",
["fortress"] = "ha recibido "..allachiv_eventdata["fortress"].." puntos de daño",
["dmgnodmg"] = "ha esquivado todos los ataques e inflingido "..allachiv_eventdata["dmgnodmg"].." puntos de daño",
["whipit"] = "ha azotado por "..allachiv_eventdata["whipit"].." puntos de daño",
["whack"] = "ha golpeado por "..allachiv_eventdata["whack"].." puntos de daño",
["bullseye"] = "ha disparado por "..allachiv_eventdata["bullseye"].." puntos de daño",
["sheep"] = "ha matado, por su propia cuenta, a Ewecus",
["tentacruel"] = "ha matado, por su propia cuenta, "..allachiv_eventdata["tentacruel"].." pilares de tentáculos",
--Boss
["santa"] = "ha derrotado a Klaus!",
["dragonfly"] = "ha derrotado a Dragonfly!",
["malbatross"] = "ha derrotado a Malbatross!",
["knight"] = "ha derrotado a Shadow Knight Level 3!",
["bishop"] = "ha derrotado a Shadow Bishop Level 3!",
["rook"] = "ha derrotado a Shadow Rook Level 3!",
["minotaur"] = "ha derrotado a Ancient Guardian!",
["ancient"] = "ha derrotado a Ancient Fuelreaver!",
["rigid"] = "ha derrotado a Misery Toadstool!",
["queen"] = "ha derrotado a Bee Queen!",
["crabking"] = "ha derrotado a Crab King",
["king"] = "ha derrotado a los jefes de las estaciones!",
--Misc
["intogame"] = "ha entrado en el juego",
["superstar"] = "ha gastado "..allachiv_eventdata["superstar"].." estrellas en ventajas",
["trader"] = "ha vendido baratijas a cambio de pepitas de oro",
["knowledge"] = "ha aprendido una tradición secreta y antigüa",
["dance"] = "ha expresado sus sentimientos hacia los demás",
["teleport"] = "ha practicado transferir materia entre planos diferentes",
["birchnut"] = "ha talado "..allachiv_eventdata["birchnut"].." abedules monstruosos",
--Emer
["eatgold"] = "ha comido palillo de tambor/huevos dorado en oro "..allachiv_eventdata["eatgold"].." veces",
["eatefc"] = "ha comido Pollo Frito de Emerville "..allachiv_eventdata["eatefc"].." veces",
["eathorn"] = "ha comido cuerno de Guardián "..allachiv_eventdata["eathorn"].." vez",
["eateye"] = "ha comido ojo de Deerclops "..allachiv_eventdata["eateye"].." vez",
["emerald"] = "ha conseguido "..allachiv_eventdata["emerald"].." gemas verdes",
["goldcoin"] = "ha conseguido "..allachiv_eventdata["goldcoin"].." monedas de oro",
["baronsuit"] = "ha conseguido "..allachiv_eventdata["baronsuit"].." Baron's suit",
--["luck"] = "ha obtenido el saco de Krampus!",
--["citrin"] = "tiene "..allachiv_eventdata["citrin"].." gemas amarillas",
--["amber"] = "tiene "..allachiv_eventdata["amber"].." gemas naranjas",
--["saddle"] = "ha conseguido una Montura de Glossamer",
--["banana"] = "tiene "..allachiv_eventdata["banana"].." bananas de cueva cocinadas",
--["moonrock"] = "tiene "..allachiv_eventdata["moonrock"].." rocas lunares",
--["gnome"] = "tiene "..allachiv_eventdata["gnome"].." gnomos",
--Mile
["all"] = "ha completado todos los logros!",
--["intogameafterall"] = "ha empezado una segunda partida",
["longage"] = "ha sobrevivido "..allachiv_eventdata["longage"].." días",
["oldage"] = "ha sobrevivido "..allachiv_eventdata["oldage"].." días",
["walkalot"] = "ha caminado por "..(allachiv_eventdata["walkalot"]/60).." minutos",
["stopalot"] = "ha permanecido inmóbil por "..(allachiv_eventdata["stopalot"]/60).." minutos",
["caveage"] = "ha permanecido en las cuevas "..(allachiv_eventdata["caveage"]/60).." minutos",
["rider"] = "ha montado un Beefalo por "..(allachiv_eventdata["rider"]/60).." minutos",
["fullsanity"] = "se ha mantenido sano por "..(allachiv_eventdata["fullsanity"]/60).." minutos",
["fullhunger"] = "no ha sufrido hambre por "..(allachiv_eventdata["fullhunger"]/60).." minutos",
["pacifist"] = "no ha dañado a nadie por "..(allachiv_eventdata["pacifist"]/60).." minutos",
}